---

- name: download helm and install
  block:
    - name: download helm  
      get_url:
        url: "https://get.helm.sh/helm-v{{ m7s_helm_version }}-linux-amd64.tar.gz"
        dest: /tmp/helm.tar.gz
        mode: '0770'
      run_once: true
      delegate_to: localhost
        
    - name: Extract helm.tar.gz
      unarchive:
        src: /tmp/helm.tar.gz
        dest: /tmp/  # this generate a /tmp/linux-amd64 folder
      run_once: true
      delegate_to: localhost

    - name: copy helm binary to /usr/sbin
      copy:
        src: /tmp/linux-amd64/helm
        dest: /usr/local/bin/helm
        owner: root
        group: root
        mode: '0770'
    
    - name: copy tiller binary to /usr/sbin
      copy:
        src: /tmp/linux-amd64/tiller
        dest: /usr/local/bin/tiller
        owner: root
        group: root
        mode: '0770'
  always:  
    - name: clean temporary files
      file:
        state: absent
        path: /tmp/linux-amd64
      run_once: true
      delegate_to: localhost
      ignore_errors: yes

    - name: clean helm.tar.gz
      file:
        state: absent
        path: /tmp/helm.tar.gz
      run_once: true
      delegate_to: localhost
      ignore_errors: yes
