---

- name: create service account
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: tiller
        namespace: kube-system

- name: create cluster role binding account
  k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: tiller
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
      - kind: ServiceAccount
        name: tiller
        namespace: kube-system

- name: install tiller (but not! upgrade)
  command: /usr/local/bin/helm init --service-account tiller --history-max {{ k8s_helm_history_max }}
  when:
    - k8s_helm_upgrade == false

- name: install and upgrade tiller
  command: /usr/local/bin/helm init --service-account tiller --history-max {{ k8s_helm_history_max }} --upgrade
  when:
    - k8s_helm_upgrade == true