---
# tasks file for k8s-helm
  
- name: try invoke helm
  command: helm
  register: helm_output
  when: 
  - m7s_helm_enabled

- name: set if helm is installed
  set_fact:
    helm_installed: helm_output.rc == 0 and m7s_helm_enabled

- name: check helm client version
  shell: helm version -c | egrep -o "[0-9]+\.[0-9]+\.[0-9]+"
  register: helm_output
  when: 
  - helm_installed

- name: set actual version if helm is installed
  set_fact:
    helm_version: helm_output.stdout
  when:
  - helm_output.rc is defined

- include_tasks: linux-install-helm.yml
  when: 
  - m7s_helm_state != 'purged'
  - helm_version is defined
  - helm_version is version(m7s_helm_version[1:],'<') or helm_installed == false

- include_tasks: linux-install-tiller.yml
  when:
  - m7s_helm_state != 'purged'
  - helm_version is defined
  - helm_version is version(m7s_helm_version[1:],'<') or helm_installed == false